[build]
  publish = "public"
  command = "true"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
